####
POST http://localhost:5000/reviews
Content-Type: application/json

{
    "book_title": "Dertogada",
    "review": "Its a good book"
}


### 
GET http://localhost:5000/reviews

### 
GET http://localhost:5000/reviews/100

###
PATCH  http://localhost:5000/reviews/4
Content-Type: application/json

{
    "review": "changed"
}

### 
DELETE  http://localhost:5000/reviews/4